### ISSUE TITLE
Icons on jquery mobile elements broken

### ISSUE THREAD

**Issue by fa11enangel** [dmarkow/jquery-mobile-rails#6]
The arrow icons on listing and the home icon button are broken in version 1.0.2 and 1.0.3. The problem doesn't exist on 1.0.1.

**Comment by tscolari** [comment]
Hi, could you give a try on v 1.0.4? I just released it.
I updated jquery mobile to v1.0.1, and re-generated all assets links in the css.

**Comment by fa11enangel** [comment]
I've checked v 1.0.4 and the problem is still there. I've checked it on iphone, android and firefox (with user agent switcher).

**Comment by tscolari** [comment]
I update my mobile sample app with this version (http://mobile-sample-app.heroku.com/) and it seems to be working for me.
Can you paste a piece of the html code that you are using?

**Comment by fa11enangel** [comment]
I found the reason. Previos to v 1.0.2 you used erb and simple css files (jquery.mobile.css.erb). After v 1.0.1 you changed it from erb to scss (jquery.mobile.css.scss). But I use less, that's why the files didn't compile. Thank you for your help.

Please add this information on your readme file, thank you.
